### ISSUE TITLE
Caret jumps to end in URL field.

### ISSUE THREAD

**Issue by domdfcoding** [bskinn/soi-app#32]
While typing in the URL field, if the caret is placed at the beginning (or in the middle) of any text already entered, it jumps to the end after inserting one character. 

This recording demonstrates what happens:
![Peek 2022-11-28 11-00](https://user-images.githubusercontent.com/8050853/204261723-b964b665-b604-42e1-b2a3-d36e77457363.gif)

It doesn't happen on the "Search Term" or "Score Threshold" fields, just URL. I think it's related to the validation and the red border. If I change the field's type from "url" to "text" it behaves.

**Comment by bskinn** [comment]
Agreed, the validation is too aggressive... I think the best solution is to add `debounce=True` to the input field; in my testing just now, that led to the red box still appearing for text without the scheme, but didn't jump the cursor to the end of the field.

It's probably still a good idea to retain the URL validation, though, because `sphobjinv` requires the scheme to be present in order to download a file -- it doesn't try to do any inference.

Patch should be live shortly. Thanks for the report!

**Comment by bskinn** [comment]
Fix is live, see what you think.
